#!/usr/bin/env node
'use strict';

const exec = require('child_process').exec;
const path = require('path');
const mkdirp = require('mkdirp');
const fs = require('fs');
const argv = process.argv;
const outDir = path.join(process.cwd(), argv[2]);

mkdirp.sync(outDir);

const scripts = [
  ['./props context action', 'action-context-types.json'],
  ['./hits YYYY-MM-DD', 'hits-per-day.json'],
  ['./hits YYYY-MM-DD-HH', 'hits-per-hour.json'],
  ['./hits YYYY-MM-DD-HH-mm', 'hits-per-minute.json'],
  ['./actions YYYY-MM-DD', 'actions-per-day.json'],
  ['./actions YYYY-MM-DD-HH', 'actions-per-hour.json'],
  ['./actions YYYY-MM-DD-HH-mm', 'actions-per-minute.json'],
  ['./actions total YYYY-MM-DD', 'total-actions-per-day.json'],
  ['./actions total YYYY-MM-DD-HH', 'total-actions-per-hour.json'],
  ['./actions total YYYY-MM-DD-HH-mm', 'total-actions-per-minute.json'],
  ['./uniques YYYY-MM-DD', 'uniques-per-day.json'],
  ['./uniques YYYY-MM-DD-HH', 'uniques-per-hour.json'],
  ['./uniques YYYY-MM-DD-HH-mm', 'uniques-per-minute.json']
];

process.stdin.setMaxListeners(15);

scripts.forEach(function(s) {
  const cmd = s[0];
  const outFile = s[1];

  const script = exec(cmd);

  process.stdin.pipe(script.stdin);
  script.stdout.pipe(fs.createWriteStream(path.join(outDir, outFile)));
});
