'use strict';

var trainerActions = [
  ["course","view"],
  ["resource","view"],
  ["user","login"],
  ["role","unassign"],
  ["user","logout"],
  ["role","assign"],
  ["course","enrol"],
  ["folder","view"],
  ["quiz","continue attempt"],
  ["forum","view forum"],
  ["choicegroup","view"],
  ["login","error"],
  ["forum","view discussion"],
  ["course","update mod"],
  ["assign","view"],
  ["choice","view"],
  ["course","unenrol"],
  ["url","view"],
  ["user","view all"],
  ["data","view"],
  ["page","view"],
  ["quiz","view"],
  ["course","editsection"],
  ["course","add mod"],
  ["book","view chapter"],
  ["quiz","review"],
  ["user","delete"],
  ["course","view section"],
  ["user","view"],
  ["resource","add"],
  ["course","delete mod"],
  ["assign","view submit assignment form"],
  ["choice","choose"],
  ["glossary","view"],
  ["choicegroup","choose"],
  ["assign","view submission grading table"],
  ["assign","submit"],
  ["quiz","editquestions"],
  ["quiz","view summary"],
  ["mediathek","view"],
  ["quiz","attempt"],
  ["quiz","close attempt"],
  ["resource","update"],
  ["vhb","access"],
  ["course","recent"],
  ["user","update"],
  ["feedback","view"],
  ["assign","grade submission"],
  ["forum","add discussion"],
  ["book","view"],
  ["assign","view confirm submit assignment form"],
  ["wiki","view"],
  ["assign","view grading form"],
  ["user","add"],
  ["label","update"],
  ["assign","submit for grading"],
  ["course","update"],
  ["book","update chapter"],
  ["garbagecollector","setAuthNoLogin"],
  ["course","new"],
  ["choice","choose again"],
  ["lesson","view"],
  ["forum","delete discussion"],
  ["feedback","delete"],
  ["data","add"],
  ["folder","edit"],
  ["quiz","preview"],
  ["forum","add post"],
  ["glossary","update entry"],
  ["assign","submission statement accepted"],
  ["mediaconnector","retrieve"],
  ["page","update"],
  ["quiz","delete attempt"],
  ["feedback","submit"],
  ["label","add"],
  ["url","add"],
  ["choicegroup","remove choice"],
  ["quiz","manualgrade"],
  ["assign","update"],
  ["quiz","report"],
  ["calendar","add"],
  ["message","write"],
  ["course","maxenrol"],
  ["choice","report"],
  ["hotpot","view"],
  ["hotpot","attempt"],
  ["label","view all"],
  ["url","view all"],
  ["lightboxgallery","view all"],
  ["book","view all"],
  ["folder","view all"],
  ["page","view all"],
  ["imscp","view all"],
  ["resource","view all"],
  ["quiz","update"],
  ["lightboxgallery","view"],
  ["grade","update"],
  ["scorm","launch"],
  ["hotpot","submit"],
  ["forum","view forums"],
  ["url","update"],
  ["folder","add"],
  ["etherpadlite","view"],
  ["course","delete"],
  ["forum","search"],
  ["calendar","edit"],
  ["glossary","view entry"],
  ["data","view all"],
  ["glossary","add entry"],
  ["choice","update"],
  ["forum","update post"],
  ["choicegroup","report"],
  ["choicegroup","update"],
  ["chat","view"],
  ["forum","update"],
  ["wiki","edit"],
  ["scorm","pre-view"],
  ["data","record delete"],
  ["folder","update"],
  ["adobeconnect","view"],
  ["lesson","start"],
  ["message","add contact"],
  ["data","update"],
  ["forum","add"],
  ["scorm","view"],
  ["mindmap","view"],
  ["course","move"],
  ["chat","report"],
  ["wiki","history"],
  ["category","add"],
  ["book","print"],
  ["data","templates view"],
  ["wiki","comments"],
  ["page","add"],
  ["adobeconnect","join meeting"],
  ["book","add chapter"],
  ["assign","add"],
  ["quiz","view all"],
  ["choicegroup","view all"],
  ["quiz","add"],
  ["book","update"],
  ["assign","view all"],
  ["category","update"],
  ["feedback","update"],
  ["wiki","map"],
  ["course","report log"],
  ["assign","download all submissions"],
  ["category","hide"],
  ["lightboxgallery","editimage"],
  ["category","delete"],
  ["scorm","update"],
  ["hotpot","update"],
  ["choicegroup","choose again"],
  ["forum","view subscribers"],
  ["data","templates saved"],
  ["mediathek","add"],
  ["choice","add"],
  ["blog","view"],
  ["forum","subscribe"],
  ["wiki","add page"],
  ["book","print chapter"],
  ["choice","view all"],
  ["lesson","end"],
  ["choicegroup","add"],
  ["data","fields add"],
  ["category","show"],
  ["forum","move discussion"],
  ["message","remove contact"],
  ["survey","view form"],
  ["course","report outline"],
  ["chat","talk"],
  ["forum","unsubscribe"],
  ["data","fields update"],
  ["chat","view all"],
  ["etherpadlite","add"],
  ["assign","lock submission"],
  ["hotpot","report"],
  ["scorm","report"],
  ["assign","revert submission to draft"],
  ["wiki","update"],
  ["imscp","view"],
  ["assign","view submission"],
  ["mediathek","update"],
  ["glossary","add"],
  ["lightboxgallery","update"],
  ["course","completion updated"],
  ["chat","add"],
  ["feedback","add"],
  ["wiki","comment"],
  ["book","add"],
  ["hotpot","add"],
  ["adobeconnect","add"],
  ["mindmap","update"],
  ["forum","delete post"],
  ["wiki","add"],
  ["hotpot","view all"],
  ["scorm","add"],
  ["glossary","delete entry"],
  ["survey","update"],
  ["etherpadlite","update"],
  ["wiki","admin"],
  ["chat","update"],
  ["lightboxgallery","add"],
  ["message","block contact"],
  ["adobeconnect","update"],
  ["wiki","diff"],
  ["message","view"],
  ["mindmap","add"],
  ["course","report stats"],
  ["forum","mark read"],
  ["survey","add"],
  ["workshop","view"],
  ["role","override"],
  ["glossary","update"],
  ["course","report live"],
  ["discussion","mark read"],
  ["data","fields delete"],
  ["message","unblock contact"],
  ["lesson","add"],
  ["notes","view"],
  ["forum","stop tracking"],
  ["blog","add"],
  ["workshop","add"],
  ["workshop","update"],
  ["survey","view graph"],
  ["forum","unsubscribeall"],
  ["assign","view feedback"],
  ["survey","submit"],
  ["feedback","view all"],
  ["blog","update"],
  ["forum","subscribeall"],
  ["mindmap","view all"],
  ["course","report participation"],
  ["forum","start tracking"],
  ["scorm","delete attempts"],
  ["survey","view report"],
  ["assign","unlock submission"],
  ["calendar","edit all"],
  ["glossary","view all"],
  ["mediathek","view all"],
  ["lesson","view all"],
  ["course","user report"]
];

module.exports = trainerActions;